# Generated by Django 4.0.1 on 2022-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterField(
            model_name='post',
            name='nombre_imagen',
            field=models.ImageField(upload_to='post_files'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sumario',
            field=models.CharField(max_length=150),
        ),
    ]
