# Generated by Django 4.0.1 on 2022-02-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_autor_options_alter_post_nombre_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('usuario_email', models.EmailField(max_length=254)),
                ('usuario_mensaje', models.TextField(max_length=1500)),
                ('usuario_fecha_comment', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
