# Generated by Django 4.0.1 on 2022-02-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentForm',
            new_name='CommentModel',
        ),
    ]
