# Generated by Django 4.0.1 on 2022-02-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_commentform_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='usuario_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
