# Generated by Django 4.0.1 on 2022-02-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commentmodel_usuario_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.FileField(upload_to='post_files'),
        ),
    ]
