# Generated by Django 4.0.1 on 2022-02-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=models.TextField(max_length=50000, null=True),
        ),
    ]
