# Generated by Django 4.0.1 on 2022-02-13 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='usuario_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post'),
        ),
    ]
